name: Tag Terraform Module
description: Create git tag for TF module when VERSION file changes

inputs:
  charm-path:
    description: Path to charm directory
    required: true
  push-tag:
    description: Push the tag to remote
    default: "true"
  dry-run:
    description: Skip actual tag creation (for testing)
    default: "false"

outputs:
  tag:
    description: The created tag (if any)
    value: ${{ steps.tag.outputs.tag }}
  created:
    description: Whether a tag was created
    value: ${{ steps.tag.outputs.created }}

runs:
  using: composite
  steps:
    - name: Check VERSION and create tag
      id: tag
      shell: bash
      env:
        CHARM_PATH: ${{ inputs.charm-path }}
        PUSH_TAG: ${{ inputs.push-tag }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -euo pipefail

        version_file="${CHARM_PATH}/terraform/VERSION"
        if [[ ! -f "$version_file" ]]; then
          echo "No VERSION file found at $version_file"
          echo "tag=" >> "$GITHUB_OUTPUT"
          echo "created=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Get charm name from charmcraft.yaml
        charm_name=$(yq .name "${CHARM_PATH}/charmcraft.yaml")
        version=$(cat "$version_file")
        tag="${charm_name}-tf/v${version}"

        # Check if tag already exists
        if git rev-parse "$tag" >/dev/null 2>&1; then
          echo "Tag $tag already exists"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "created=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Check if VERSION file changed in this commit
        if ! git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -q "^${CHARM_PATH}/terraform/VERSION$"; then
          echo "VERSION file not changed"
          echo "tag=" >> "$GITHUB_OUTPUT"
          echo "created=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        if [[ "$DRY_RUN" == "true" ]]; then
          echo "DRY-RUN: Would create tag $tag"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "created=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Create and optionally push tag
        git tag "$tag"
        echo "Created tag: $tag"

        if [[ "$PUSH_TAG" == "true" ]]; then
          git push origin "$tag"
          echo "Pushed tag: $tag"
        fi

        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        echo "created=true" >> "$GITHUB_OUTPUT"
