name: Cleanup Charm Environment
description: Cleanup charm development environment

runs:
  using: composite
  steps:
    - name: Restore concierge
      shell: bash
      run: sudo concierge restore
