name: Publish Charm to Charmhub
description: Upload charm and release to a channel

inputs:
  charm-path:
    description: Path to charm directory
    required: true
  channel:
    description: Charmhub channel to release to (e.g., "latest/edge", "1/stable")
    required: true
  artifact-name:
    description: Name of the artifact to download
    default: charm
  dry-run:
    description: Skip actual upload/release (for testing)
    default: "false"

outputs:
  revision:
    description: The uploaded charm revision
    value: ${{ steps.publish.outputs.revision }}

runs:
  using: composite
  steps:
    - name: Download charm artifact
      uses: actions/download-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.charm-path }}

    - name: Publish to Charmhub
      id: publish
      shell: bash
      working-directory: ${{ inputs.charm-path }}
      env:
        CHANNEL: ${{ inputs.channel }}
        DRY_RUN: ${{ inputs.dry-run }}
        # CHARMHUB_TOKEN must be set by the calling workflow
        CHARMCRAFT_AUTH: ${{ env.CHARMHUB_TOKEN }}
      run: |
        set -euo pipefail

        if [[ -z "${CHARMCRAFT_AUTH:-}" ]]; then
          echo "::error::CHARMHUB_TOKEN environment variable not set"
          exit 1
        fi

        charm_file="$(find . -maxdepth 1 -name '*.charm' -print -quit)"
        if [[ -z "$charm_file" ]]; then
          echo "::error::No .charm file found"
          exit 1
        fi
        charm_name=$(yq .name charmcraft.yaml)

        if [[ "$DRY_RUN" == "true" ]]; then
          echo "DRY-RUN: Would upload $charm_file"
          echo "DRY-RUN: Would release $charm_name to $CHANNEL"
          echo "revision=dry-run" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Upload charm
        upload_result=$(charmcraft upload "$charm_file" --format=json)
        revision=$(echo "$upload_result" | jq -r '.revision')
        echo "Uploaded revision: $revision"

        # Build resource flags for release command
        resource_flags=""

        # Check for OCI image resources in charmcraft.yaml
        resources=$(yq -o=json '.resources // {}' charmcraft.yaml)
        for resource_name in $(echo "$resources" | jq -r 'keys[]'); do
          resource_type=$(echo "$resources" | jq -r --arg name "$resource_name" '.[$name].type')
          if [[ "$resource_type" == "oci-image" ]]; then
            upstream=$(echo "$resources" | jq -r --arg name "$resource_name" '.[$name]["upstream-source"]')
            echo "Uploading OCI resource: $resource_name ($upstream)"
            resource_result=$(charmcraft upload-resource "$charm_name" "$resource_name" --image="docker://$upstream" --format=json)
            resource_rev=$(echo "$resource_result" | jq -r '.revision')
            echo "Uploaded resource revision: $resource_rev"
            resource_flags="$resource_flags --resource=$resource_name:$resource_rev"
          fi
        done

        # Release to channel
        charmcraft release "$charm_name" --revision="$revision" --channel="$CHANNEL" $resource_flags
        echo "Released to: $CHANNEL"

        echo "revision=$revision" >> "$GITHUB_OUTPUT"
