name: Setup Charm Environment
description: Install tools for charm development and CI

inputs:
  charmcraft:
    description: Install charmcraft
    default: "true"
  lxd:
    description: Setup LXD for building charms
    default: "false"
  juju:
    description: Setup Juju and K8s substrate via concierge
    default: "false"
  substrate:
    description: K8s substrate (microk8s or k8s)
    default: "microk8s"
  substrate-channel:
    description: Substrate snap channel
    default: "1.32-strict/stable"
  juju-channel:
    description: Juju snap channel
    default: "3.6/stable"
  charmcraft-channel:
    description: Charmcraft snap channel
    default: "latest/stable"
  extra-debs:
    description: Additional apt packages to install (comma-separated)
    default: ""
  automatically-retry-hooks:
    description: Whether Juju should automatically retry failed hooks
    default: "true"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"

    - name: Install yq
      shell: bash
      run: sudo snap install yq

    - name: Install charmcraft
      if: inputs.charmcraft == 'true'
      shell: bash
      run: sudo snap install charmcraft --classic --channel="${{ inputs.charmcraft-channel }}"

    - name: Setup LXD
      if: inputs.lxd == 'true'
      uses: canonical/setup-lxd@main

    - name: Setup Juju and K8s substrate via concierge
      if: inputs.juju == 'true'
      shell: bash
      env:
        CONCIERGE_JUJU_CHANNEL: ${{ inputs.juju-channel }}
        CONCIERGE_MICROK8S_CHANNEL: ${{ inputs.substrate-channel }}
        CONCIERGE_K8S_CHANNEL: ${{ inputs.substrate-channel }}
        CONCIERGE_CHARMCRAFT_CHANNEL: ${{ inputs.charmcraft-channel }}
      run: |
        sudo snap install concierge --classic
        extra_debs_flag=""
        if [[ -n "${{ inputs.extra-debs }}" ]]; then
          extra_debs_flag="--extra-debs=${{ inputs.extra-debs }}"
        fi
        sudo concierge prepare -p "${{ inputs.substrate }}" --extra-snaps=astral-uv $extra_debs_flag
        sudo snap install kubectl --classic
        juju model-defaults automatically-retry-hooks="${{ inputs.automatically-retry-hooks }}"
