name: 'Commitlint'
description: 'Validate commit messages follow conventional commits'

inputs:
  base-sha:
    description: 'Base commit SHA to compare from'
    required: false
    default: ''
  head-sha:
    description: 'Head commit SHA to compare to'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout with history
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Install commitlint
      shell: bash
      run: npm install -g @commitlint/cli @commitlint/config-conventional

    - name: Validate commits
      shell: bash
      run: |
        BASE_SHA="${{ inputs.base-sha }}"
        HEAD_SHA="${{ inputs.head-sha }}"

        # Default to PR SHAs if not provided
        if [ -z "$BASE_SHA" ]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
        fi
        if [ -z "$HEAD_SHA" ]; then
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
        fi

        # Create config
        echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

        # Run commitlint
        npx commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --verbose
